# Generated by Django 5.1.1 on 2024-09-16 12:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("dashboard", "0002_stock_sn"),
    ]

    operations = [
        migrations.AlterField(
            model_name="stock",
            name="sn",
            field=models.IntegerField(default=0, null=True),
        ),
    ]
