# Generated by Django 5.1.1 on 2024-09-16 13:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("dashboard", "0003_alter_stock_sn"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="movestock",
            name="stock",
        ),
        migrations.AddField(
            model_name="movestock",
            name="stocks",
            field=models.ManyToManyField(
                null=True, related_name="move_stocks", to="dashboard.stock"
            ),
        ),
    ]
