# Generated by Django 5.1.1 on 2024-09-16 15:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("dashboard", "0004_remove_movestock_stock_movestock_stocks"),
    ]

    operations = [
        migrations.RenameField(
            model_name="movestock",
            old_name="stocks",
            new_name="materials",
        ),
        migrations.RemoveField(
            model_name="orderrequisition",
            name="customer_address",
        ),
        migrations.RemoveField(
            model_name="orderrequisition",
            name="customer_number",
        ),
        migrations.RemoveField(
            model_name="orderrequisition",
            name="material_description",
        ),
        migrations.RemoveField(
            model_name="orderrequisition",
            name="material_name",
        ),
        migrations.RemoveField(
            model_name="orderrequisition",
            name="material_number",
        ),
        migrations.RemoveField(
            model_name="orderrequisition",
            name="unit_price",
        ),
        migrations.RemoveField(
            model_name="orderrequisition",
            name="unit_type",
        ),
        migrations.AddField(
            model_name="orderrequisition",
            name="materials",
            field=models.ManyToManyField(
                related_name="order_requisitions", to="dashboard.stock"
            ),
        ),
    ]
