# Generated by Django 5.1.1 on 2024-09-16 21:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("dashboard", "0005_rename_stocks_movestock_materials_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="movestock",
            name="materials",
        ),
        migrations.RemoveField(
            model_name="orderrequisition",
            name="materials",
        ),
        migrations.RemoveField(
            model_name="stock",
            name="sn",
        ),
        migrations.AddField(
            model_name="movestock",
            name="stock",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="dashboard.stock",
            ),
        ),
        migrations.AddField(
            model_name="orderrequisition",
            name="customer_address",
            field=models.CharField(default="None", max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="orderrequisition",
            name="customer_number",
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="orderrequisition",
            name="material_description",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="orderrequisition",
            name="material_name",
            field=models.CharField(max_length=55, null=True),
        ),
        migrations.AddField(
            model_name="orderrequisition",
            name="material_number",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="order_requisition",
                to="dashboard.stock",
            ),
        ),
        migrations.AddField(
            model_name="orderrequisition",
            name="unit_price",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
        migrations.AddField(
            model_name="orderrequisition",
            name="unit_type",
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
