# Generated by Django 5.1.1 on 2024-09-16 21:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("dashboard", "0006_remove_movestock_materials_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="stock",
            name="sn",
            field=models.IntegerField(default=0, null=True),
        ),
    ]
