# Generated by Django 5.1.1 on 2024-09-17 00:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("dashboard", "0008_rename_date_movestock_date_created_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="stock",
            name="source",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="inventorylocation",
            name="stock",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="dashboard.stock",
            ),
        ),
        migrations.AlterField(
            model_name="stock",
            name="exp_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="stock",
            name="sn",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="stock",
            name="stocks_committed",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="stock",
            name="stocks_on_hand",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="stock",
            name="stored_stocks",
            field=models.IntegerField(default=0),
        ),
    ]
