# Generated by Django 5.1.1 on 2024-09-17 12:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("dashboard", "0009_stock_source_alter_inventorylocation_stock_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="orderrequisition",
            name="total_price",
            field=models.DecimalField(
                blank=True, decimal_places=3, max_digits=10, null=True
            ),
        ),
    ]
