# Generated by Django 5.1.1 on 2024-09-17 15:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("dashboard", "0010_alter_orderrequisition_total_price"),
    ]

    operations = [
        migrations.AlterField(
            model_name="movestock",
            name="total_price",
            field=models.FloatField(default=0),
        ),
    ]
