# Generated by Django 5.1.1 on 2024-09-17 15:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("dashboard", "0011_alter_movestock_total_price"),
    ]

    operations = [
        migrations.AlterField(
            model_name="movestock",
            name="total_price",
            field=models.DecimalField(
                blank=True, decimal_places=3, default=0, max_digits=10, null=True
            ),
        ),
        migrations.AlterField(
            model_name="orderrequisition",
            name="total_price",
            field=models.DecimalField(
                blank=True, decimal_places=3, default=0, max_digits=10, null=True
            ),
        ),
    ]
