# Generated by Django 5.1.1 on 2024-09-17 19:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("dashboard", "0013_remove_materialorder_move_stock_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="materialbound",
            name="in_movestock",
        ),
        migrations.RemoveField(
            model_name="materialbound",
            name="material",
        ),
        migrations.RemoveField(
            model_name="materialbound",
            name="out_move_stock",
        ),
        migrations.RemoveField(
            model_name="outboundmovestock",
            name="material_bound",
        ),
        migrations.RemoveField(
            model_name="outboundmovestock",
            name="order_requisition",
        ),
        migrations.RemoveField(
            model_name="outboundmovestock",
            name="responsible_staff",
        ),
        migrations.AddField(
            model_name="orderrequisition",
            name="material_order",
            field=models.ManyToManyField(
                related_name="order_requisitions",
                through="dashboard.MaterialOrder",
                to="dashboard.stock",
            ),
        ),
        migrations.AddField(
            model_name="stock",
            name="exp_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="stock",
            name="source",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="materialorder",
            name="order_requisition",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="material_orders",
                to="dashboard.orderrequisition",
            ),
        ),
        migrations.CreateModel(
            name="MoveStock",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "movement_type",
                    models.CharField(
                        choices=[
                            ("procurement", "Procurement"),
                            ("fulfillment", "Fulfillment"),
                        ],
                        max_length=50,
                    ),
                ),
                ("date_created", models.DateTimeField(auto_now_add=True)),
                (
                    "total_price",
                    models.DecimalField(
                        blank=True,
                        decimal_places=3,
                        default=0,
                        max_digits=10,
                        null=True,
                    ),
                ),
                ("exp_date", models.DateField(blank=True, null=True)),
                ("source", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "material_order",
                    models.ManyToManyField(
                        related_name="move_stocks",
                        through="dashboard.MaterialOrder",
                        to="dashboard.stock",
                    ),
                ),
                (
                    "order_requisition_number",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="dashboard.orderrequisition",
                    ),
                ),
                (
                    "responsible_staff",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="materialorder",
            name="move_stock",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="material_orders",
                to="dashboard.movestock",
            ),
        ),
        migrations.DeleteModel(
            name="InboundMoveStock",
        ),
        migrations.DeleteModel(
            name="MaterialBound",
        ),
        migrations.DeleteModel(
            name="OutboundMoveStock",
        ),
    ]
