# Generated by Django 5.1.1 on 2024-09-19 22:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("dashboard", "0015_stock_threshold"),
    ]

    operations = [
        migrations.AlterField(
            model_name="stock",
            name="threshold",
            field=models.FloatField(),
        ),
    ]
