# Generated by Django 5.1.1 on 2024-09-19 23:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("dashboard", "0016_alter_stock_threshold"),
    ]

    operations = [
        migrations.AddField(
            model_name="materialorder",
            name="expiration_date",
            field=models.DateTimeField(null=True),
        ),
    ]
