# Generated by Django 5.1.1 on 2024-09-19 23:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("dashboard", "0017_materialorder_expiration_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="materialorder",
            name="expiration_date",
            field=models.DateField(null=True),
        ),
    ]
