# Generated by Django 5.1.1 on 2024-09-20 23:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("dashboard", "0018_alter_materialorder_expiration_date"),
    ]

    operations = [
        migrations.CreateModel(
            name="MaterialQuantity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantity", models.FloatField()),
                (
                    "material",
                    models.ManyToManyField(
                        related_name="material_quantity",
                        through="dashboard.MaterialOrder",
                        to="dashboard.stock",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="materialorder",
            name="mq",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="dashboard.materialquantity",
            ),
        ),
    ]
