# Generated by Django 5.1.1 on 2024-09-20 23:59

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("dashboard", "0019_materialquantity_materialorder_mq"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="materialorder",
            name="mq",
        ),
        migrations.DeleteModel(
            name="MaterialQuantity",
        ),
    ]
