# Generated by Django 5.1.1 on 2024-09-21 12:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("dashboard", "0020_remove_materialorder_mq_delete_materialquantity"),
    ]

    operations = [
        migrations.AlterField(
            model_name="stock",
            name="threshold",
            field=models.FloatField(default=0),
        ),
    ]
