# Generated by Django 5.1.1 on 2024-09-21 12:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("dashboard", "0021_alter_stock_threshold"),
    ]

    operations = [
        migrations.AddField(
            model_name="stock",
            name="material_order",
            field=models.ManyToManyField(
                related_name="stocks",
                through="dashboard.MaterialOrder",
                to="dashboard.movestock",
            ),
        ),
    ]
