# Generated by Django 5.1.1 on 2024-09-21 12:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("dashboard", "0022_stock_material_order"),
    ]

    operations = [
        migrations.AlterField(
            model_name="materialorder",
            name="quantity",
            field=models.IntegerField(),
        ),
    ]
