# Generated by Django 5.1.1 on 2024-09-21 13:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("dashboard", "0023_alter_materialorder_quantity"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="materialorder",
            name="order_requisition",
        ),
        migrations.CreateModel(
            name="MaterialOrderRequistion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantity", models.IntegerField(null=True)),
                (
                    "material",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="dashboard.stock",
                    ),
                ),
                (
                    "order_requisition",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="material_orders",
                        to="dashboard.orderrequisition",
                    ),
                ),
            ],
        ),
        migrations.AlterField(
            model_name="orderrequisition",
            name="material_order",
            field=models.ManyToManyField(
                related_name="order_requisitions",
                through="dashboard.MaterialOrderRequistion",
                to="dashboard.stock",
            ),
        ),
    ]
