# Generated by Django 5.1.1 on 2024-09-21 13:34

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("dashboard", "0024_remove_materialorder_order_requisition_and_more"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="MaterialOrderRequistion",
            new_name="MaterialOrderRequisition",
        ),
    ]
