# Generated by Django 5.1.1 on 2024-09-21 15:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("dashboard", "0025_rename_materialorderrequistion_materialorderrequisition"),
    ]

    operations = [
        migrations.CreateModel(
            name="MaterialOrderReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantity", models.IntegerField()),
                ("expiration_date", models.DateField(null=True)),
                (
                    "material",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="dashboard.stock",
                    ),
                ),
                (
                    "move_stock",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="material_order_reports",
                        to="dashboard.movestock",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="movestock",
            name="material_order_report",
            field=models.ManyToManyField(
                related_name="move_stock_reports",
                through="dashboard.MaterialOrderReport",
                to="dashboard.stock",
            ),
        ),
    ]
