# Generated by Django 5.1.1 on 2024-09-21 16:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("dashboard", "0026_materialorderreport_movestock_material_order_report"),
    ]

    operations = [
        migrations.AlterField(
            model_name="materialorder",
            name="quantity",
            field=models.PositiveIntegerField(),
        ),
    ]
