# Generated by Django 5.1.1 on 2024-09-21 21:24

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("dashboard", "0027_alter_materialorder_quantity"),
    ]

    operations = [
        migrations.AddField(
            model_name="materialorder",
            name="active",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="materialorder",
            name="sold_date",
            field=models.DateField(default=django.utils.timezone.now, null=True),
        ),
    ]
