# Generated by Django 5.1.1 on 2024-09-21 21:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("dashboard", "0028_materialorder_active_materialorder_sold_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="materialorder",
            name="sold_date",
            field=models.DateField(null=True),
        ),
    ]
