# Generated by Django 5.1.1 on 2024-09-21 21:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("dashboard", "0029_alter_materialorder_sold_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="materialorderrequisition",
            name="active",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="materialorderrequisition",
            name="sold_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
