# Generated by Django 5.1.1 on 2024-09-21 21:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("dashboard", "0030_materialorderrequisition_active_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="materialorderrequisition",
            name="number_sold",
            field=models.IntegerField(default=0),
        ),
    ]
