# Generated by Django 5.1.1 on 2024-09-21 22:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("dashboard", "0031_materialorderrequisition_number_sold"),
    ]

    operations = [
        migrations.AddField(
            model_name="materialorder",
            name="number_sold",
            field=models.IntegerField(default=0),
        ),
    ]
