# Generated by Django 5.1.1 on 2024-10-09 20:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("dashboard", "0034_remove_stock_material_order_inbound_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="stock",
            name="material_order",
            field=models.ManyToManyField(
                related_name="stocks",
                through="dashboard.MaterialOrder",
                to="dashboard.movestock",
            ),
        ),
    ]
