# Generated by Django 5.1.1 on 2024-10-09 22:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("dashboard", "0035_stock_material_order"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="materialorder",
            name="inbound",
        ),
        migrations.RemoveField(
            model_name="materialorder",
            name="outbound",
        ),
        migrations.CreateModel(
            name="MaterialInbound",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantity", models.PositiveIntegerField()),
                ("expiration_date", models.DateField(null=True)),
                (
                    "inbound",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="material_inbounds",
                        to="dashboard.inbound",
                    ),
                ),
                (
                    "material",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="dashboard.stock",
                    ),
                ),
            ],
        ),
        migrations.AlterField(
            model_name="inbound",
            name="material_order",
            field=models.ManyToManyField(
                related_name="inbound",
                through="dashboard.MaterialInbound",
                to="dashboard.stock",
            ),
        ),
        migrations.CreateModel(
            name="MaterialOutbound",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantity", models.PositiveIntegerField()),
                ("sold_date", models.DateField(null=True)),
                ("number_sold", models.IntegerField(default=0)),
                (
                    "material",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="dashboard.stock",
                    ),
                ),
                (
                    "outbound",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="material_outbounds",
                        to="dashboard.outbound",
                    ),
                ),
            ],
        ),
        migrations.AlterField(
            model_name="outbound",
            name="material_order",
            field=models.ManyToManyField(
                related_name="outbound",
                through="dashboard.MaterialOutbound",
                to="dashboard.stock",
            ),
        ),
    ]
