# Generated by Django 5.1.1 on 2024-10-10 00:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("dashboard", "0036_remove_materialorder_inbound_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="stock",
            name="material_order",
        ),
        migrations.AddField(
            model_name="materialinbound",
            name="active",
            field=models.BooleanField(default=True),
        ),
    ]
