# Generated by Django 5.1.1 on 2024-10-10 16:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("dashboard", "0037_remove_stock_material_order_materialinbound_active"),
    ]

    operations = [
        migrations.AlterField(
            model_name="materialorderreport",
            name="inbound",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="material_inbound_reports",
                to="dashboard.inbound",
            ),
        ),
        migrations.AlterField(
            model_name="materialorderreport",
            name="outbound",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="material_outbound_reports",
                to="dashboard.outbound",
            ),
        ),
    ]
