# Generated by Django 5.1.1 on 2024-10-10 16:29

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("dashboard", "0038_alter_materialorderreport_inbound_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="inbound",
            old_name="material_order",
            new_name="material_inbound",
        ),
        migrations.RenameField(
            model_name="inbound",
            old_name="material_order_report",
            new_name="material_inbound_report",
        ),
    ]
