# Generated by Django 5.1.1 on 2024-10-13 10:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("dashboard", "0039_rename_material_order_inbound_material_inbound_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="stock",
            name="image",
            field=models.ImageField(default="avatar.jpg", upload_to="stock_images/"),
        ),
    ]
